### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by hpatoio** [bluef/trac-git-graph#1]
Hello. How do you install this plugin ? Tried with `easy_install https://github.com/bluef/trac-git-graph.git` but no luck.

**Comment by eregion** [comment]
In short: 
 # wget -c https://github.com/bluef/trac-git-graph/archive/master.zip
 # unzip master.zip
 # cd trac-git-graph-master/
 # chmod +x setup.py
 # ./setup.py build
 # ./setup.py install
 # /etc/init.d/tracd restart

**Comment by hpatoio** [comment]
Thanks. I thought about installing it from the source. Just didn't know it there where a `easy_install` way to do it.
